2017-11-29 19:09:35,061 - requests.packages.urllib3 - INFO - Response content: b'{\n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Cookie": "_gauges_unique_day=1; _gauges_unique_month=1; _gauges_unique_year=1; _gauges_unique=1; _gauges_unique_hour=1", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }\n}\n'
2017-11-29 19:09:35,062 - root - ERROR - pytest_runtest_call caught exception:
Traceback (most recent call last):
  File "C:\vKalendare\project_tinkoff\conftest.py", line 19, in pytest_runtest_call
    __multicall__.execute()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 130, in execute
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\runner.py", line 107, in pytest_runtest_call
    item.runtest()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 1171, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 201, in _multicall
    return outcome.get_result()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 147, in pytest_pyfunc_call
    testfunction(**testargs)
  File "C:\vKalendare\project_tinkoff\tests\test_first.py", line 18, in test_header
    assert not 'headers' in resp_json
AssertionError: assert not 'headers' in {'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7', 'Connection': 'close', ...}}
2017-11-29 19:09:35,106 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:35,683 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/200 HTTP/1.1" 200 0
2017-11-29 19:09:35,707 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:35,714 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:36,296 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/201 HTTP/1.1" 201 0
2017-11-29 19:09:36,300 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:36,306 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:36,897 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/400 HTTP/1.1" 400 0
2017-11-29 19:09:36,900 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:36,914 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:37,485 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/403 HTTP/1.1" 403 0
2017-11-29 19:09:37,495 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:37,503 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:38,085 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/404 HTTP/1.1" 404 0
2017-11-29 19:09:38,088 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:38,097 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:38,673 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/500 HTTP/1.1" 500 0
2017-11-29 19:09:38,676 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:09:38,683 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:39,255 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/1 HTTP/1.1" 302 215
2017-11-29 19:09:39,257 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:09:39,840 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:09:39,844 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:09:39,851 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:09:40,427 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/3 HTTP/1.1" 302 247
2017-11-29 19:09:40,441 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:09:41,039 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/2 HTTP/1.1" 302 0
2017-11-29 19:09:41,041 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:09:41,619 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/1 HTTP/1.1" 302 0
2017-11-29 19:09:41,622 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:09:42,198 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:09:42,208 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:12:12,884 - requests.packages.urllib3 - INFO - Response content: b'{\n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Cookie": "_gauges_unique_day=1; _gauges_unique_month=1; _gauges_unique_year=1; _gauges_unique=1; _gauges_unique_hour=1", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }\n}\n'
2017-11-29 19:12:12,885 - root - ERROR - pytest_runtest_call caught exception:
Traceback (most recent call last):
  File "C:\vKalendare\project_tinkoff\conftest.py", line 19, in pytest_runtest_call
    __multicall__.execute()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 130, in execute
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\runner.py", line 107, in pytest_runtest_call
    item.runtest()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 1171, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 201, in _multicall
    return outcome.get_result()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 147, in pytest_pyfunc_call
    testfunction(**testargs)
  File "C:\vKalendare\project_tinkoff\tests\test_first.py", line 18, in test_header
    assert not 'headers' in resp_json
AssertionError: assert not 'headers' in {'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7', 'Connection': 'close', ...}}
2017-11-29 19:12:12,932 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:13,513 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/200 HTTP/1.1" 200 0
2017-11-29 19:12:13,548 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:13,560 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:14,134 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/201 HTTP/1.1" 201 0
2017-11-29 19:12:14,136 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:14,142 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:14,719 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/400 HTTP/1.1" 400 0
2017-11-29 19:12:14,722 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:14,736 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:15,317 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/403 HTTP/1.1" 403 0
2017-11-29 19:12:15,329 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:15,344 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:15,938 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/404 HTTP/1.1" 404 0
2017-11-29 19:12:15,944 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:16,040 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:16,628 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/500 HTTP/1.1" 500 0
2017-11-29 19:12:16,631 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:12:16,640 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:17,220 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/1 HTTP/1.1" 302 215
2017-11-29 19:12:17,222 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:12:17,807 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:12:17,810 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:12:17,816 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:12:18,452 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/3 HTTP/1.1" 302 247
2017-11-29 19:12:18,460 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:12:19,039 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/2 HTTP/1.1" 302 0
2017-11-29 19:12:19,043 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:12:19,622 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/1 HTTP/1.1" 302 0
2017-11-29 19:12:19,624 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:12:20,202 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:12:20,214 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:25:04,265 - requests.packages.urllib3 - INFO - Response content: b'{\n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Cookie": "_gauges_unique_day=1; _gauges_unique_month=1; _gauges_unique_year=1; _gauges_unique=1; _gauges_unique_hour=1", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }\n}\n'
2017-11-29 19:25:04,274 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:04,848 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/200 HTTP/1.1" 200 0
2017-11-29 19:25:04,856 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:04,862 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:05,447 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/201 HTTP/1.1" 201 0
2017-11-29 19:25:05,451 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:05,457 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:06,037 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/400 HTTP/1.1" 400 0
2017-11-29 19:25:06,040 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:06,134 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:06,704 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/403 HTTP/1.1" 403 0
2017-11-29 19:25:06,707 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:06,748 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:07,322 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/404 HTTP/1.1" 404 0
2017-11-29 19:25:07,329 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:07,335 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:07,910 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /status/500 HTTP/1.1" 500 0
2017-11-29 19:25:07,913 - requests.packages.urllib3 - INFO - Response content: b''
2017-11-29 19:25:07,923 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:08,505 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/1 HTTP/1.1" 302 215
2017-11-29 19:25:08,507 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:25:09,080 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:25:09,083 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:25:09,092 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): httpbin.org
2017-11-29 19:25:09,667 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /redirect/3 HTTP/1.1" 302 247
2017-11-29 19:25:09,669 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:25:10,242 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/2 HTTP/1.1" 302 0
2017-11-29 19:25:10,244 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:25:10,831 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /relative-redirect/1 HTTP/1.1" 302 0
2017-11-29 19:25:10,840 - urllib3.connectionpool - DEBUG - Resetting dropped connection: httpbin.org
2017-11-29 19:25:11,447 - urllib3.connectionpool - DEBUG - https://httpbin.org:443 "GET /get HTTP/1.1" 200 612
2017-11-29 19:25:11,455 - requests.packages.urllib3 - INFO - Response content: b'{\n  "args": {}, \n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", \n    "Accept-Encoding": "gzip, deflate, br", \n    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7", \n    "Connection": "close", \n    "Host": "httpbin.org", \n    "Referer": "https://httpbin.org/", \n    "Upgrade-Insecure-Requests": "1", \n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36", \n    "X-Compress": "null"\n  }, \n  "origin": "5.23.97.158", \n  "url": "https://httpbin.org/get"\n}\n'
2017-11-29 19:25:11,460 - root - ERROR - pytest_runtest_call caught exception:
Traceback (most recent call last):
  File "C:\vKalendare\project_tinkoff\conftest.py", line 19, in pytest_runtest_call
    __multicall__.execute()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 130, in execute
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\runner.py", line 107, in pytest_runtest_call
    item.runtest()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 1171, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 201, in _multicall
    return outcome.get_result()
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "C:\vKalendare\venv36_tinkoff\lib\site-packages\_pytest\python.py", line 147, in pytest_pyfunc_call
    testfunction(**testargs)
  File "C:\vKalendare\project_tinkoff\tests\test_first.py", line 50, in test_log_assert_false
    assert False
AssertionError: assert False
